# Trigger build for all branches
trigger:
  batch: true
  branches:
    include:
    - '*'

pr:
  autoCancel: false
  branches:
    include:
    - master
    - release/*

variables:
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: 1
- name: BUILD_NUMBER
  value: $[counter('buildnumber', 1)]

jobs:
- template: /build/templates/job.yml
  parameters:
    name: $(AgentOs)
    enablePublishBuildAssets: true
    pool: $(Pool)
    strategy:
      matrix:
        Windows:
          AgentOs: Windows_NT
          Pool: Windows
          BuildConfiguration: Release
        Linux:
          AgentOs: Linux
          Pool: Linux
          BuildConfiguration: Release

    workspace:
      clean: outputs
    
    steps:
#    - powershell: echo "##vso[task.setvariable variable=DotnetVersion] $(((Get-Content "global.json" -Raw) | ConvertFrom-Json).sdk.version)"
#      displayName: 'Set .NET Core version from global.json'
    
    - task: UseDotNet@2
      displayName: 'Install .NET Core sdk'
      inputs:
        packageType: sdk
#        version: $(DotnetVersion)
        version: 3.x
        includePreviewVersions: true
    
    - powershell: ./build.ps1 -ci --Configuration $(BuildConfiguration)
      displayName: Invoke build.ps1
    
    - task: PublishTestResults@2
      displayName: Upload test results
      condition: always()
      continueOnError: true
      inputs:
        testRunner: vstest
        testResultsFiles: '**/*.trx'
    
    - task: PublishBuildArtifacts@1
      displayName: Publish artifacts
      inputs:
        pathtoPublish: 'artifacts/'
        artifactName: 'Packages'
