# Trigger build for all branches
trigger:
  batch: true
  branches:
    include:
    - '*'

pr:
  autoCancel: false
  branches:
    include:
    - master
    - release/*

variables:
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: 1
- name: BUILD_NUMBER
  value: $[counter('buildnumber', 1)]

workspace:
  clean: outputs

steps:
#- powershell: echo "##vso[task.setvariable variable=DotnetVersion] $(((Get-Content "global.json" -Raw) | ConvertFrom-Json).sdk.version)"
#  displayName: 'Set .NET Core version from global.json'

- task: DotNetCoreInstaller@0
  displayName: 'Install .NET Core'
  inputs:
    packageType: 'sdk'
#    version: $(DotnetVersion)
    version: '3.x'
    includePreviewVersions: true

- powershell: ./build.ps1 -ci
  displayName: Invoke build.ps1

- task: PublishTestResults@2
  displayName: Upload test results
  condition: always()
  continueOnError: true
  inputs:
    testRunner: vstest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1
  displayName: Publish artifacts
  inputs:
    pathtoPublish: 'artifacts/'
    artifactName: 'Packages'
